version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    entrypoint:
      - /sbin/init
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app:cached
    tty: true
  redis:
    image: redis
